/*
 * March 29
 * fastfood ordering program
 */

/**
 *
 * @author eli
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        burgerlabel = new javax.swing.JLabel();
        frieslabel = new javax.swing.JLabel();
        sodalabel = new javax.swing.JLabel();
        numberOfBurgers = new javax.swing.JTextField();
        numberOfFries = new javax.swing.JTextField();
        numberOfSodas = new javax.swing.JTextField();
        enter1 = new javax.swing.JButton();
        priceb4taxlabel = new javax.swing.JLabel();
        taxlabel = new javax.swing.JLabel();
        posttaxpricelabel = new javax.swing.JLabel();
        tenderedlabel = new javax.swing.JLabel();
        changelabel = new javax.swing.JLabel();
        priceB4 = new javax.swing.JLabel();
        taxDisplay = new javax.swing.JLabel();
        priceFinal = new javax.swing.JLabel();
        amountTendered = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        $fromcostumer = new javax.swing.JTextField();
        changeReturned = new javax.swing.JLabel();
        enter2 = new javax.swing.JButton();
        imagelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 153, 51));

        Title.setFont(new java.awt.Font("Monaco", 0, 18)); // NOI18N
        Title.setText("Welcome, please enter your order!");

        burgerlabel.setText("# of Burgers:");

        frieslabel.setText("# of french fries orders:");

        sodalabel.setText("# of sodas:");

        numberOfBurgers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfBurgersActionPerformed(evt);
            }
        });

        enter1.setText("Enter");
        enter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter1ActionPerformed(evt);
            }
        });

        priceb4taxlabel.setText("Price before tax:");

        taxlabel.setText("Tax:");

        posttaxpricelabel.setText("Price After Tax:");

        tenderedlabel.setText("Amount Tendered:");

        changelabel.setText("Change:");

        priceB4.setText("$");

        taxDisplay.setText("$");

        priceFinal.setText("$");

        enter2.setText("Enter");
        enter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter2ActionPerformed(evt);
            }
        });

        imagelabel.setIcon(new javax.swing.ImageIcon("/Users/eli/Downloads/ls.jpg")); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changelabel)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tenderedlabel)
                                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(priceb4taxlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(taxlabel)
                                        .addComponent(posttaxpricelabel)))
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(amountTendered)
                                            .addComponent(priceFinal)
                                            .addComponent(taxDisplay)
                                            .addComponent(priceB4)
                                            .addComponent(change)))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(changeReturned)
                                            .addComponent($fromcostumer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                                .addComponent(burgerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(84, 84, 84))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                                                .addComponent(frieslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64))))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(sodalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numberOfSodas, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(numberOfFries)
                                    .addComponent(numberOfBurgers)))
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enter2)
                                    .addComponent(enter1))))
                        .addGap(72, 72, 72)
                        .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burgerlabel)
                    .addComponent(numberOfBurgers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frieslabel)
                    .addComponent(numberOfFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sodalabel)
                            .addComponent(numberOfSodas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enter1)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceb4taxlabel)
                            .addComponent(priceB4))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxlabel)
                            .addComponent(taxDisplay))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(posttaxpricelabel)
                            .addComponent(priceFinal))
                        .addGap(46, 46, 46)
                        .addComponent(amountTendered)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(change)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenderedlabel)
                            .addComponent($fromcostumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enter2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changelabel)
                    .addComponent(changeReturned))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfBurgersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfBurgersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfBurgersActionPerformed

    private void enter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter1ActionPerformed
        //declaring the constant values, such as the price of each item and hst
        final double hst, BPRICE, FPRICE, PPRICE;
        hst = 1.13;
        BPRICE = 2.49;
        FPRICE = 1.89;
        PPRICE = 0.99;
        //gets the user to enter a value and turns it into an integer
        double numB, numF, numP;
        numB = Integer.parseInt(numberOfBurgers.getText());
        numF = Integer.parseInt(numberOfFries.getText());
        numP = Integer.parseInt(numberOfSodas.getText());
        //calculates the cost of the food without and with tax, also formating it to two decimal places, like currency
        double $beforetax = Math.round((numB*BPRICE+numF*FPRICE+numP*PPRICE)*100.0)/100.0;
        double taxation = Math.round(($beforetax*0.13)*100.0)/100.0;
        double total_price = Math.round((hst*$beforetax)*100.0)/100.0;
        //displays the various costs
        priceB4.setText(Double.toString($beforetax));
        taxDisplay.setText(Double.toString(taxation));
        priceFinal.setText(Double.toString(total_price));
        
       
        
        
    }//GEN-LAST:event_enter1ActionPerformed

    private void enter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter2ActionPerformed
         double tendered, change, total_price;
         total_price = Double.parseDouble(priceFinal.getText());
        tendered = Double.parseDouble($fromcostumer.getText());
        tendered = Math.round((tendered*100.0)/100.0);
        change = tendered-total_price;//calculates the change based on how much the costumer pasy
        changeReturned.setText(Double.toString(change)); //displasy the change to a  text field
    }//GEN-LAST:event_enter2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField $fromcostumer;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel amountTendered;
    private javax.swing.JPanel background;
    private javax.swing.JLabel burgerlabel;
    private javax.swing.JLabel change;
    private javax.swing.JLabel changeReturned;
    private javax.swing.JLabel changelabel;
    private javax.swing.JButton enter1;
    private javax.swing.JButton enter2;
    private javax.swing.JLabel frieslabel;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JTextField numberOfBurgers;
    private javax.swing.JTextField numberOfFries;
    private javax.swing.JTextField numberOfSodas;
    private javax.swing.JLabel posttaxpricelabel;
    private javax.swing.JLabel priceB4;
    private javax.swing.JLabel priceFinal;
    private javax.swing.JLabel priceb4taxlabel;
    private javax.swing.JLabel sodalabel;
    private javax.swing.JLabel taxDisplay;
    private javax.swing.JLabel taxlabel;
    private javax.swing.JLabel tenderedlabel;
    // End of variables declaration//GEN-END:variables
}
